twitter-monitor.yml example
newrelic/nri-flex pull request #222
Opened 2020-09-10 08:56 UTC by CharlieWinters

Twitter integration from the flex webinar: https://newrelic.com/resources/webinars/your-observability-data-in-one-place1

2020-09-10 08:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/nri-flex?pullRequest=222) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/nri-flex?pullRequest=222) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/nri-flex?pullRequest=222) it.</sub>

2020-09-14 15:52 UTC, thezackm requested changes

2020-09-14 15:52 UTC, thezackm commented on examples/twitter-monitor.yml
> +      lookup_file: /home/ubuntu/apikeys.json
please add a sample lookup JSON file to this PR to be submitted with this config.
ref: [example](https://github.com/newrelic/nri-flex/blob/master/examples/openssl-expiration-lookup.json)

2020-09-17 13:23 UTC, thezackm requested changes
looks solid, please rename to `twitter-monitor-lookup.json` and we should be ready to rock!

2020-09-17 13:56 UTC, CharlieWinters commented
Thanks @thezackm, changed now, also changed the name in the  twitter-monitor.yml to match.

2020-09-17 14:02 UTC, thezackm approved these changes
let's GTM

2020-09-17 14:12 UTC, merged