Add example for Elastic APM Integration
newrelic/nri-flex pull request #237
Opened 2020-10-23 01:14 UTC by ericmittelhammer

Queries Elasticsearch for `Transaction`, `Metric`, and `Error` events collected by Elastic APM

2020-10-23 01:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/nri-flex?pullRequest=237) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/nri-flex?pullRequest=237) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/nri-flex?pullRequest=237) it.</sub>

2020-10-27 18:20 UTC, thezackm requested changes
please make the following edits:

* move files from `examples/elastic-apm/*` to `examples/*`
* The event limit is set to 500 by default, but it is a [configurable option](https://github.com/newrelic/nri-flex/blob/af2f8cb41fa9f221b2bc1768ecb2698902176d05/configs/nri-flex-config-linux.yml#L21) in the `env:` attribute; please add the option, commented out, to the samples; or a note in the top comments if you think it would be a common problem

2020-10-27 21:35 UTC, ericmittelhammer commented
@thezackm: addressed those changes.

2020-10-27 21:43 UTC, thezackm approved these changes

2020-10-27 21:44 UTC, merged